### ISSUE TITLE
Needs a twist. 

### ISSUE THREAD

**Issue by rewolff** [ErroneousBosch/OpenSCAD_airfoil#1]
Many wings have a twist in them. One of the reasons for this is "stall recovery". A normal wing is swept back a bit. By having the AOA lower at the tips and higher in the middle, when the wing stalls, the center part, that normally provides lift in front of the center of gravity loses lift, so the nose is no longer supported and drops to gain speed and get out of the stall

A picture where you can see this: 
https://www.offset.com/photos/a-tandem-hang-gliders-taking-off-above-the-hillside-of-pedro-bonita-317044

I have implemented a rudimentary twist, and it works, except that the "hull" operation will add some unwanted volume. So we'll need to interpolate both the airfoil and  the twist and provide many more intermediate slices to make things smooth. 

I will be looking into separating the airfoil generation from the naca code extraction. If I want to blend from say 4425 to 4415 we'll need a 44(1.5)5 in the middle. I think the formulas would allow for that, the naca coding doesn't.

**Comment by ErroneousBosch** [comment]
Interesting. I had originally designed this for basic turbine airfoils, but I'll have to dig back into it.

One approach would be to allow it to take the NACA equivalent as an array of the four numbers to plug in. I will experiment and see.

**Comment by ErroneousBosch** [comment]
I am not sure the best way to implement a twist, since where the twist happens is too dependent on specific usecase, and coding for that is beyond the scope of what I wanted to accomplish. The simple wing is meant to be just that. More complex wings can be accomplished with end user logic an multiple calls to the `airfoil_poly` to generate sub-shapes, then using hull or extrusions. 

I have added a `raw` option that allows a vector array to pass the three ratios calculated out from the NACA code directly and allow for more fine grained control.
